// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Server.Models;

public partial class Consumable
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// biolog; mecanic
    /// </summary>
    public string Design { get; set; }

    public string ValueFormat { get; set; }

    /// <summary>
    /// SUBSTANCE;DEVICE;CONSUMABLE;
    /// </summary>
    public string ValueType { get; set; }

    /// <summary>
    /// Descriptive field
    /// </summary>
    public string MeasureUnit { get; set; }

    public virtual ICollection<AnesthesiaConsumable> AnesthesiaConsumables { get; } = new List<AnesthesiaConsumable>();

    public virtual ConsumableCategory Category { get; set; }

    public virtual ICollection<Cecconsumable> Cecconsumables { get; } = new List<Cecconsumable>();
}