// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Server.Models;

/// <summary>
/// Will be sincronised with users table; Medical staff is managed by NOW another app, but that may change
/// </summary>
public partial class Medic
{
    public int Id { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// optional: medic&apos; seal
    /// </summary>
    public string Code { get; set; }

    public string Specialty { get; set; }

    public string Note { get; set; }

    public virtual ICollection<MedicPatient> MedicPatients { get; } = new List<MedicPatient>();
}