// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Server.Models;

public partial class PatientTreatment
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int TreatmentId { get; set; }

    /// <summary>
    /// The treatment may be related to a specific diagnostic. or not
    /// </summary>
    public int? PatientDiagnosticId { get; set; }

    /// <summary>
    /// Tratament (default); Anestezie;CEC;PRIMARY; SECONDARY; ATI; OTHER
    /// </summary>
    public string TreatmentType { get; set; }

    public int? NoOfDays { get; set; }

    public string WeekSchema { get; set; }

    public decimal Dosage { get; set; }

    public decimal? DosageQtty { get; set; }

    public decimal? DosageTotal { get; set; }

    public string Administration { get; set; }

    public string DosageNote { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual ICollection<PatientDailyTreatment> PatientDailyTreatments { get; } = new List<PatientDailyTreatment>();

    public virtual Treatment Treatment { get; set; }
}