// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Server.Models;

/// <summary>
/// Patient details; contains only &apos;fixed details&apos; the variable ones (like weight, height, BMI...) are included in patient&apos;s file
/// </summary>
public partial class Patient
{
    public int Id { get; set; }

    /// <summary>
    /// Social Security Number; Romanian CNP is 13 digits length; Newborns may not have it
    /// </summary>
    public string Cnp { get; set; }

    /// <summary>
    /// Prenume
    /// </summary>
    public string FirstName { get; set; }

    /// <summary>
    /// NUme
    /// </summary>
    public string LastName { get; set; }

    public string Cnascode { get; set; }

    /// <summary>
    /// Data nasterii
    /// </summary>
    public DateTime BirthDate { get; set; }

    public string Sex { get; set; }

    /// <summary>
    /// Grupa Sangvina
    /// </summary>
    public string BloodGroup { get; set; }

    public string ParentName { get; set; }

    /// <summary>
    /// General comments
    /// </summary>
    public string Note { get; set; }

    /// <summary>
    /// COPIL = child; Not directly related to age but to the specific of the medical procedures
    /// </summary>
    public string ChildOrAdult { get; set; }

    public virtual ICollection<MedicPatient> MedicPatients { get; } = new List<MedicPatient>();

    public virtual ICollection<PatientAssocDisease> PatientAssocDiseases { get; } = new List<PatientAssocDisease>();

    public virtual ICollection<PatientFile> PatientFiles { get; } = new List<PatientFile>();

    public virtual ICollection<PatientTreatment> PatientTreatments { get; } = new List<PatientTreatment>();
}