// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Server.Models;

public partial class PatientDiagnostic
{
    public int Id { get; set; }

    /// <summary>
    /// optional; PatientFile is enough
    /// </summary>
    public int PatientId { get; set; }

    public int PatientFileId { get; set; }

    public int DiagnosticId { get; set; }

    public DateTime Date { get; set; }

    /// <summary>
    /// Value is formated acording to diagnostic.ValueFormat
    /// </summary>
    public string Value { get; set; }

    public string ShortNote { get; set; }

    public virtual Diagnostic Diagnostic { get; set; }

    public virtual PatientFile PatientFile { get; set; }
}