// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Server.Models;

public partial class SurgeryAnesthesium
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int PatientFileId { get; set; }

    public int PatientSurgeryId { get; set; }

    public DateTime? Date { get; set; }

    public int Duration { get; set; }

    public string Name { get; set; }

    public virtual ICollection<AnesthesiaConsumable> AnesthesiaConsumables { get; } = new List<AnesthesiaConsumable>();

    public virtual PatientSurgery PatientSurgery { get; set; }
}