// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

/// <summary>
/// extracorporeal circulation
/// </summary>
public partial class Cec
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int PatientSurgeryId { get; set; }

    public int BypasDuration { get; set; }

    public decimal? BypasTemperature { get; set; }

    /// <summary>
    /// It may be an interval; first version will only suport the medium value (Celsius)
    /// </summary>
    public decimal? BypasTemperatureTop { get; set; }

    public int? AorticClampingDuration { get; set; }

    public decimal? AorticClampingTemperature { get; set; }

    /// <summary>
    /// It may be an interval; first version will only suport the medium value (Celsius)
    /// </summary>
    public decimal? AorticClampingTemperatureTop { get; set; }

    public decimal? Flow { get; set; }

    public decimal? Priming { get; set; }

    public string? Oxigenator { get; set; }

    public bool? Muff { get; set; }

    public bool? Ultrafiltering { get; set; }

    public string? Note { get; set; }

    public virtual ICollection<CecConsumable> CecConsumables { get; } = new List<CecConsumable>();

    public virtual PatientSurgery PatientSurgery { get; set; } = null!;
}