// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class CecConsumable
{
    public int Id { get; set; }

    public int Cecid { get; set; }

    public int ConsumableId { get; set; }

    public string Value { get; set; } = null!;

    /// <summary>
    /// Computed from Value, if the Format is type Numeric
    /// </summary>
    public decimal? NumericValue { get; set; }

    public string? ShortNote { get; set; }

    public virtual Cec Cec { get; set; } = null!;

    public virtual Consumable Consumable { get; set; } = null!;
}