// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class Cecconsumable
{
    public int Id { get; set; }

    public int Cecid { get; set; }

    public int ConsumableId { get; set; }

    public string Value { get; set; }

    public string ShortNote { get; set; }

    public virtual Cec Cec { get; set; }

    public virtual Consumable Consumable { get; set; }
}