// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

/// <summary>
/// type of consumables used in surgery
/// </summary>
public partial class ConsumableCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Consumable> Consumables { get; } = new List<Consumable>();
}