// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

/// <summary>
/// type of consumables used in surgery
/// </summary>
public partial class ConsumableCategory
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    /// <summary>
    /// Default measure unit if any; but it may be used another one (subdivision / concentration...) at affective use of the consumable
    /// </summary>
    public string? MeasureUnit { get; set; }

    //public virtual ICollection<Consumable> Consumables { get; } = new List<Consumable>();
}