// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class Consumable
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public string Name { get; set; } = null!;

    /// <summary>
    /// biolog; mecanic
    /// </summary>
    public string? Design { get; set; }

    public string ValueFormat { get; set; } = null!;

    /// <summary>
    /// SUBSTANCE;DEVICE;CONSUMABLE;
    /// </summary>
    public string Type { get; set; } = null!;

    /// <summary>
    /// Descriptive field
    /// </summary>
    public string? MeasureUnit { get; set; }

    public virtual ICollection<AnesthesiaConsumable> AnesthesiaConsumables { get; } = new List<AnesthesiaConsumable>();

    public virtual ConsumableCategory Category { get; set; } = null!;

    public virtual ICollection<CecConsumable> CecConsumables { get; } = new List<CecConsumable>();
}