// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

/// <summary>
/// Categories: gruping the diagnoses
/// </summary>
public partial class DiagnosticCategory
{
    public int Id { get; set; }

    /// <summary>
    /// Medical conditions types / groups - uzually the name of the web page
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Values: PRIMARY; SECONDARY; ATI; OTHER
    /// </summary>
    public string Type { get; set; }

    public virtual ICollection<Diagnostic> Diagnostics { get; } = new List<Diagnostic>();
}