// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

/// <summary>
/// Will be sincronised with users table; Medical staff is managed by NOW another app, but that may change
/// </summary>
public partial class Medic
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Email { get; set; } = null!;

    /// <summary>
    /// optional: medic&apos; seal
    /// </summary>
    public string? Code { get; set; }

    public string? Specialty { get; set; }

    public string? Note { get; set; }

    public byte[]? PasswordHash { get; set; }

    public byte[]? PasswordSalt { get; set; }

    public bool IsConfirmed { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<MedicPatient> MedicPatients { get; } = new List<MedicPatient>();
}