// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

/// <summary>
/// Contains default parameters used in app. Critical pamaters are hard coded, but they can be extended if required
/// </summary>
public partial class Param
{
    /// <summary>
    /// Separated by ;
    /// </summary>
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Value { get; set; }

    /// <summary>
    /// Usually only critical params will be added
    /// </summary>
    public bool? Critical { get; set; }
}