// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class PatientDailyTreatment
{
    public int Id { get; set; }

    public int TreatmentId { get; set; }

    /// <summary>
    /// Date and Hour of administering the substances
    /// </summary>
    public DateTime? AdministrationTime { get; set; }

    public string Dosage { get; set; } = null!;

    public decimal? DosageNumeric { get; set; }

    public decimal? DosageQtty { get; set; }

    /// <summary>
    /// Medical observations due treatment administration if any
    /// </summary>
    public string? Note { get; set; }

    public virtual PatientTreatment Treatment { get; set; } = null!;
}