// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class PatientSurgery
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int PatientFileId { get; set; }

    /// <summary>
    /// Date of the surgery
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Incision type
    /// </summary>
    public string IncisionType { get; set; }

    /// <summary>
    /// Minutes
    /// </summary>
    public int? Duration { get; set; }

    /// <summary>
    /// Minutes
    /// </summary>
    public int? Cecduration { get; set; }

    /// <summary>
    /// Minutes
    /// </summary>
    public int? AorticClampDuration { get; set; }

    /// <summary>
    /// Yes/No (null=NoNo=No; any other obs means Yes)
    /// </summary>
    public bool? Reoperation { get; set; }

    public string Complications { get; set; }

    public DateTime? ReoperationDate { get; set; }

    public virtual ICollection<Cec> Cecs { get; } = new List<Cec>();

    public virtual PatientFile PatientFile { get; set; }

    public virtual ICollection<Surgery> Surgeries { get; } = new List<Surgery>();

    public virtual ICollection<SurgeryAnesthesium> SurgeryAnesthesia { get; } = new List<SurgeryAnesthesium>();
}