// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class PatientTreatment
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int TreatmentId { get; set; }

    /// <summary>
    /// The treatment may be related to a specific diagnostic. or not
    /// </summary>
    public int? PatientDiagnosticId { get; set; }

    /// <summary>
    /// obsolete; not used for now
    /// </summary>
    public string TreatmentType { get; set; } = null!;

    public int? NoOfDays { get; set; }

    /// <summary>
    /// It represent a bit field: 1 or 0 for each day of the week ; depends on treatment-&gt;Administration Mode
    /// </summary>
    public string? WeekSchema { get; set; }

    /// <summary>
    /// List of possible routes; it can be a sublist from the Treatmnt-&gt;Administration Route 
    /// </summary>
    public string? AdministrationRoute { get; set; }

    /// <summary>
    /// List of possible routes; it can be a sublist from the Treatmnt-&gt;Administeringration Mode
    /// </summary>
    public string? AdministrationMode { get; set; }

    public string Value { get; set; } = null!;

    public decimal? NumericValue { get; set; }

    /// <summary>
    /// If interval, the second value will be stored here
    /// </summary>
    public decimal? ValueInterval { get; set; }

    public decimal? DosageQtty { get; set; }

    public decimal? Total { get; set; }

    /// <summary>
    /// Specific info about Dosage or values
    /// </summary>
    public string? ValueNote { get; set; }

    /// <summary>
    /// Medical observations, complications... any
    /// </summary>
    public string? Note { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }
}