// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class PatientDiagnostic
{
    public int Id { get; set; }

    /// <summary>
    /// optional; PatientFile is enough
    /// </summary>
    public int PatientId { get; set; }

    public int PatientFileId { get; set; }

    public int DiagnosticId { get; set; }

    public DateTime Date { get; set; }

    /// <summary>
    /// Value is formated acording to diagnostic.ValueFormat
    /// </summary>
    public string? Value { get; set; }

    public decimal? NumericValue { get; set; }

    public string? ShortNote { get; set; }

    /// <summary>
    /// Preoperator=0r; intraoperator/intrasurgery=1 (in time of the surgery or before)
    /// </summary>
    public bool IntraSurgery { get; set; }

    public virtual Diagnostic Diagnostic { get; set; } = null!;

    public virtual PatientFile PatientFile { get; set; } = null!;
}