// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class SurgicalProcedure
{
    public int Id { get; set; }

    /// <summary>
    /// Just one degree of circular relation parent-&gt;son; 
    /// </summary>
    public int ParentId { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<Surgery> Surgeries { get; } = new List<Surgery>();
}