// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class SurgeryAnesthesium
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int PatientFileId { get; set; }

    public int PatientSurgeryId { get; set; }

    public DateTime Date { get; set; }

    public int Duration { get; set; }

    public string Name { get; set; } = null!;

    /// <summary>
    /// generala;locoreginala;bloc paravertrebral;bloc parasternal;
    /// </summary>
    public string Type { get; set; } = null!;

    /*
    public virtual ICollection<AnesthesiaConsumable> AnesthesiaConsumables { get; } = new List<AnesthesiaConsumable>();

    public virtual PatientSurgery PatientSurgery { get; set; } = null!;
    */
}