// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

/// <summary>
/// Intersection table: one surgery can have many procedures
/// </summary>
public partial class Surgery
{
    public int Id { get; set; }

    public int SurgicalCategoryId { get; set; }

    public int PatientSurgeryId { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    /*
    public virtual PatientSurgery PatientSurgery { get; set; } = null!;

    public virtual SurgicalCategory SurgicalCategory { get; set; } = null!;
    */
}