// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class Treatment
{
    public int Id { get; set; }

    public int TreatmentCategoryId { get; set; }

    public int ParentId { get; set; }

    public string Name { get; set; } = null!;

    public string? Type { get; set; }

    /// <summary>
    /// Default admin method (dosage, perfusion...) 
    /// </summary>
    public string? AdministrationMethod { get; set; }

    public string? ValueFormat { get; set; }

    public string? MeasureUnit { get; set; }
    /*
    public virtual ICollection<PatientTreatment> PatientTreatments { get; } = new List<PatientTreatment>();

    public virtual TreatmentCategory TreatmentCategory { get; set; } = null!;
    */
}