// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class Treatment
{
    public int Id { get; set; }

    public int TreatmentCategoryId { get; set; }

    public int ParentId { get; set; }

    public string Name { get; set; }

    public string ValueFormat { get; set; }

    /// <summary>
    /// Defaul admin method (dosage, perfusion...) 
    /// </summary>
    public string AdministrationMethod { get; set; }

    public virtual ICollection<PatientTreatment> PatientTreatments { get; } = new List<PatientTreatment>();

    public virtual TreatmentCategory TreatmentCategory { get; set; }
}