// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class TreatmentCategory
{
    public int Id { get; set; }

    /// <summary>
    /// description of treatment category
    /// </summary>
    public string Name { get; set; } = null!;

    public virtual ICollection<Treatment> Treatments { get; } = new List<Treatment>();
}