// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StgMures.Shared.DbModels;

public partial class TreatmentCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Treatment> Treatments { get; } = new List<Treatment>();
}