// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace StgMures.Server.Data
{
    public partial interface ISTGMuresContextProcedures
    {
    }
}
