// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using StgMures.Shared.DbModels;

namespace StgMures.Server.Data;

public partial class StgMuresContext : DbContext
{
    public StgMuresContext(DbContextOptions<StgMuresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AnesthesiaConsumable> AnesthesiaConsumables { get; set; }

    public virtual DbSet<AsociatedDisease> AsociatedDiseases { get; set; }

    public virtual DbSet<Cec> Cecs { get; set; }

    public virtual DbSet<Cecconsumable> Cecconsumables { get; set; }

    public virtual DbSet<Consumable> Consumables { get; set; }

    public virtual DbSet<ConsumableCategory> ConsumableCategories { get; set; }

    public virtual DbSet<Diagnostic> Diagnostics { get; set; }

    public virtual DbSet<DiagnosticCategory> DiagnosticCategories { get; set; }

    public virtual DbSet<Medic> Medics { get; set; }

    public virtual DbSet<MedicPatient> MedicPatients { get; set; }

    public virtual DbSet<Patient> Patients { get; set; }

    public virtual DbSet<PatientAssocDisease> PatientAssocDiseases { get; set; }

    public virtual DbSet<PatientDailyTreatment> PatientDailyTreatments { get; set; }

    public virtual DbSet<PatientDiagnostic> PatientDiagnostics { get; set; }

    public virtual DbSet<PatientFile> PatientFiles { get; set; }

    public virtual DbSet<PatientSurgery> PatientSurgeries { get; set; }

    public virtual DbSet<PatientTreatment> PatientTreatments { get; set; }

    public virtual DbSet<Surgery> Surgeries { get; set; }

    public virtual DbSet<SurgeryAnesthesium> SurgeryAnesthesia { get; set; }

    public virtual DbSet<SurgicalProcedure> SurgicalProcedures { get; set; }

    public virtual DbSet<Treatment> Treatments { get; set; }

    public virtual DbSet<TreatmentCategory> TreatmentCategories { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AnesthesiaConsumable>(entity =>
        {
            entity.ToTable("AnesthesiaConsumable");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.ConsumableId).HasColumnName("ConsumableID");
            entity.Property(e => e.ShortNote).HasMaxLength(50);
            entity.Property(e => e.SurgeryAnesthesiaId).HasColumnName("SurgeryAnesthesiaID");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.Consumable).WithMany(p => p.AnesthesiaConsumables)
                .HasForeignKey(d => d.ConsumableId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_AnesthesiaConsumable_Consumable");

            entity.HasOne(d => d.SurgeryAnesthesia).WithMany(p => p.AnesthesiaConsumables)
                .HasForeignKey(d => d.SurgeryAnesthesiaId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_AnesthesiaConsumable_SurgeryAnesthesia");
        });

        modelBuilder.Entity<AsociatedDisease>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("Contains the list of posible associated diseases a patient may have.\r\nThe primary disease usualy is a serious heart condition which determine the associated ones"));

            entity.HasIndex(e => e.Id, "IX_AsociatedDiseases");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<Cec>(entity =>
        {
            entity.ToTable("CEC", tb => tb.HasComment("extracorporeal circulation"));

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AorticClampingTemperature)
                .HasMaxLength(20)
                .IsFixedLength();
            entity.Property(e => e.BypasTemperature)
                .HasMaxLength(20)
                .IsFixedLength();
            entity.Property(e => e.Flow).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Muff).HasColumnName("MUFF");
            entity.Property(e => e.Note).HasMaxLength(250);
            entity.Property(e => e.Oxigenator).HasMaxLength(50);
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.PatientSurgeryId).HasColumnName("PatientSurgeryID");
            entity.Property(e => e.Priming).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.PatientSurgery).WithMany(p => p.Cecs)
                .HasForeignKey(d => d.PatientSurgeryId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_CEC_PatientSurgery");
        });

        modelBuilder.Entity<Cecconsumable>(entity =>
        {
            entity.ToTable("CECConsumable");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Cecid).HasColumnName("CECID");
            entity.Property(e => e.ConsumableId).HasColumnName("ConsumableID");
            entity.Property(e => e.ShortNote).HasMaxLength(50);
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.Cec).WithMany(p => p.Cecconsumables)
                .HasForeignKey(d => d.Cecid)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_CECConsumable_CEC");

            entity.HasOne(d => d.Consumable).WithMany(p => p.Cecconsumables)
                .HasForeignKey(d => d.ConsumableId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_CECConsumable_Consumable");
        });

        modelBuilder.Entity<Consumable>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Material");

            entity.ToTable("Consumable");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.Design)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("biolog; mecanic");
            entity.Property(e => e.MeasureUnit)
                .HasMaxLength(20)
                .HasComment("Descriptive field");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ValueFormat)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ValueType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("SUBSTANCE;DEVICE;CONSUMABLE;");

            entity.HasOne(d => d.Category).WithMany(p => p.Consumables)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_Consumable_ConsumableCategory");
        });

        modelBuilder.Entity<ConsumableCategory>(entity =>
        {
            entity.ToTable("ConsumableCategory", tb => tb.HasComment("type of consumables used in surgery"));

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<Diagnostic>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_MedicalCondition");

            entity.ToTable("Diagnostic", tb => tb.HasComment("Contains the list of possible diagnostics. \r\nIt is a circular database: a diagnostic can have parent (parentID is not null).\r\nA diagnostic can have multiple 'child diagnostics' (not viceversa), and I will limit the number of levels to 4.\r\nIf parent ID is not null, ValueType is ignored (null or 'p').\r\n"));

            entity.Property(e => e.Id)
                .HasComment("ValueType may be ")
                .HasColumnName("ID");
            entity.Property(e => e.DiagnosticCategoryId).HasColumnName("DiagnosticCategoryID");
            entity.Property(e => e.MaxAlertValue)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Max alert value (normal values between min and max)");
            entity.Property(e => e.MeasureUnit).HasMaxLength(50);
            entity.Property(e => e.MinAlertValue)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Min alert value (normal values between min and max); ");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150)
                .HasComment("Name of the diagnostic");
            entity.Property(e => e.Note).HasMaxLength(250);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.ValueFormat)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Determine the other fields usage: Note, MinAlert, MaxAlert ");

            entity.HasOne(d => d.DiagnosticCategory).WithMany(p => p.Diagnostics)
                .HasForeignKey(d => d.DiagnosticCategoryId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_Diagnostic_DiagnosticCategory");
        });

        modelBuilder.Entity<DiagnosticCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_MedicalGroup");

            entity.ToTable("DiagnosticCategory", tb => tb.HasComment("Categories: gruping the diagnoses"));

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150)
                .HasComment("Medical conditions types / groups - uzually the name of the web page");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsFixedLength()
                .HasComment("Values: PRIMARY; SECONDARY; ATI; OTHER");
        });

        modelBuilder.Entity<Medic>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Doctor");

            entity.ToTable("Medic", tb => tb.HasComment("It is in fact the user table; Medical staff is managed by another app, now , but that may change"));

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .HasComment("optional: medic' seal");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Note).HasMaxLength(250);
            entity.Property(e => e.Specialty).HasMaxLength(150);
            entity.Property(e => e.PasswordHash).HasMaxLength(512);
            entity.Property(e => e.PasswordSalt).HasMaxLength(512);
            entity.Property(e => e.IsConfirmed).HasColumnName("IsConfirmed");
            entity.Property(e => e.IsDeleted).HasColumnName("IsDeleted");

        });

        modelBuilder.Entity<MedicPatient>(entity =>
        {
            entity.ToTable("MedicPatient", tb => tb.HasComment("Many-to-Many relationship patient-medic"));

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.MedicId).HasColumnName("MedicID");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");

            entity.HasOne(d => d.Medic).WithMany(p => p.MedicPatients)
                .HasForeignKey(d => d.MedicId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_MedicPatient_Medic");

            entity.HasOne(d => d.Patient).WithMany(p => p.MedicPatients)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_MedicPatient_Patient");
        });

        modelBuilder.Entity<Patient>(entity =>
        {
            entity.ToTable("Patient", tb => tb.HasComment("Patient details; contains only 'fixed details' the variable ones (like weight, height, BMI...) are included in patient's file"));

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.BirthDate)
                .HasComment("Data nasterii")
                .HasColumnType("date");
            entity.Property(e => e.BloodGroup)
                //.IsRequired()
                .HasMaxLength(20)
                .HasComment("Grupa Sangvina");
            entity.Property(e => e.ChildOrAdult)
                //.IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("(N'COPIL')")
                .IsFixedLength()
                .HasComment("COPIL = child; Not directly related to age but to the specific of the medical procedures");
            entity.Property(e => e.Cnascode)
                .HasMaxLength(30)
                .IsFixedLength()
                .HasColumnName("CNASCode");
            entity.Property(e => e.Cnp)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasComment("Social Security Number; Romanian CNP is 13 digits length; Newborns may not have it")
                .HasColumnName("CNP");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(150)
                .HasComment("Prenume");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(150)
                .HasComment("NUme");
            entity.Property(e => e.Note)
                .HasMaxLength(250)
                .HasComment("General comments");
            entity.Property(e => e.ParentsName).HasMaxLength(150);
            entity.Property(e => e.Sex)
                //.IsRequired()
                .HasMaxLength(1)
                .IsFixedLength();
        });

        modelBuilder.Entity<PatientAssocDisease>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AsociatedDiseaseId)
                .HasComment("Act as a short description")
                .HasColumnName("AsociatedDiseaseID");
            entity.Property(e => e.IntraSurgery).HasComment("Determined intra-surgery");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.Symptom)
                .IsRequired()
                .HasMaxLength(2000);

            entity.HasOne(d => d.AsociatedDisease).WithMany(p => p.PatientAssocDiseases)
                .HasForeignKey(d => d.AsociatedDiseaseId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientAssocDiseases_AsociatedDiseases");

            entity.HasOne(d => d.Patient).WithMany(p => p.PatientAssocDiseases)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientAssocDiseases_Patient");
        });

        modelBuilder.Entity<PatientDailyTreatment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_DailyTreatment");

            entity.ToTable("PatientDailyTreatment");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AdministrationTime).HasColumnType("smalldatetime");
            entity.Property(e => e.Dosage).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.DosageQtty).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.Note).HasMaxLength(50);
            entity.Property(e => e.TreatmentId).HasColumnName("TreatmentID");

            entity.HasOne(d => d.Treatment).WithMany(p => p.PatientDailyTreatments)
                .HasForeignKey(d => d.TreatmentId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientDailyTreatment_PatientTreatment");
        });

        modelBuilder.Entity<PatientDiagnostic>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_DailyObservation");

            entity.ToTable("PatientDiagnostic");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DiagnosticId).HasColumnName("DiagnosticID");
            entity.Property(e => e.PatientFileId).HasColumnName("PatientFileID");
            entity.Property(e => e.PatientId)
                .HasComment("optional; PatientFile is enough")
                .HasColumnName("PatientID");
            entity.Property(e => e.ShortNote).HasMaxLength(50);
            entity.Property(e => e.Value)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasComment("Value is formated acording to diagnostic.ValueFormat");

            entity.HasOne(d => d.Diagnostic).WithMany(p => p.PatientDiagnostics)
                .HasForeignKey(d => d.DiagnosticId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientDiagnostic_Diagnostic");

            entity.HasOne(d => d.PatientFile).WithMany(p => p.PatientDiagnostics)
                .HasForeignKey(d => d.PatientFileId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientDiagnostic_PatientFile");
        });

        modelBuilder.Entity<PatientFile>(entity =>
        {
            entity.ToTable("PatientFile", tb => tb.HasComment("A patient usually has one file; but if it comes again, it may be useful to have patient's history"));

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AnotherHospitalAdmission).HasMaxLength(150);
            entity.Property(e => e.Atidays)
                .HasComment("In theory it may be calculated; but refer hospital day, not calendaristic day")
                .HasColumnName("ATIDays");
            entity.Property(e => e.AtiretakeoverDate)
                .HasColumnType("date")
                .HasColumnName("ATIRetakeoverDate");
            entity.Property(e => e.AtitakeOverDate)
                .HasColumnType("date")
                .HasColumnName("ATITakeOverDate");
            entity.Property(e => e.Bmi)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("BMI");
            entity.Property(e => e.Bsa)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("BSA");
            entity.Property(e => e.DischargeDate).HasColumnType("date");
            entity.Property(e => e.FileDate).HasColumnType("date");
            entity.Property(e => e.FileNumber)
                .HasMaxLength(20)
                .HasComment("File no asigned by user ");
            entity.Property(e => e.Height).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.HospitalAdmissionDate).HasColumnType("date");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.WardDays).HasComment("In theory it may be calculated; but refer hospital day, not calendaristic day");
            entity.Property(e => e.WardTransferDate)
                .HasComment("Data transferului pe sectie")
                .HasColumnType("date");
            entity.Property(e => e.Weight).HasColumnType("decimal(10, 3)");

            entity.HasOne(d => d.Patient).WithMany(p => p.PatientFiles)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientFile_Patient");
        });

        modelBuilder.Entity<PatientSurgery>(entity =>
        {
            entity.ToTable("PatientSurgery");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AorticClampDuration).HasComment("Minutes");
            entity.Property(e => e.Cecduration)
                .HasComment("Minutes")
                .HasColumnName("CECDuration");
            entity.Property(e => e.Complications).HasMaxLength(250);
            entity.Property(e => e.Date)
                .HasComment("Date of the surgery")
                .HasColumnType("date");
            entity.Property(e => e.Duration).HasComment("Minutes");
            entity.Property(e => e.IncisionType)
                .HasMaxLength(50)
                .HasComment("Incision type");
            entity.Property(e => e.PatientFileId).HasColumnName("PatientFileID");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.Reoperation).HasComment("Yes/No (null=NoNo=No; any other obs means Yes)");
            entity.Property(e => e.ReoperationDate).HasColumnType("date");

            entity.HasOne(d => d.PatientFile).WithMany(p => p.PatientSurgeries)
                .HasForeignKey(d => d.PatientFileId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientSurgery_PatientFile");
        });

        modelBuilder.Entity<PatientTreatment>(entity =>
        {
            entity.ToTable("PatientTreatment");

            entity.HasIndex(e => e.TreatmentId, "AK_PatientTreatment");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Administration).HasMaxLength(50);
            entity.Property(e => e.Dosage).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.DosageNote).HasMaxLength(50);
            entity.Property(e => e.DosageQtty)
                .HasDefaultValueSql("((1))")
                .HasColumnType("decimal(10, 3)");
            entity.Property(e => e.DosageTotal).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.PatientDiagnosticId)
                .HasComment("The treatment may be related to a specific diagnostic. or not")
                .HasColumnName("PatientDiagnosticID");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.TreatmentId).HasColumnName("TreatmentID");
            entity.Property(e => e.TreatmentType)
                .IsRequired()
                .HasMaxLength(20)
                .IsFixedLength()
                .HasComment("Tratament (default); Anestezie;CEC;PRIMARY; SECONDARY; ATI; OTHER");
            entity.Property(e => e.WeekSchema)
                .HasMaxLength(7)
                .IsFixedLength();

            entity.HasOne(d => d.Patient).WithMany(p => p.PatientTreatments)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientTreatment_Patient");

            entity.HasOne(d => d.Treatment).WithMany(p => p.PatientTreatments)
                .HasForeignKey(d => d.TreatmentId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientTreatment_Treatment");
        });

        modelBuilder.Entity<Surgery>(entity =>
        {
            entity.ToTable("Surgery", tb => tb.HasComment("Intersection table: one surgery can have many procedures"));

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");
            entity.Property(e => e.Description).HasMaxLength(250);
            entity.Property(e => e.PatientSurgeryId).HasColumnName("PatientSurgeryID");
            entity.Property(e => e.SurgicalProcedureId).HasColumnName("SurgicalProcedureID");

            entity.HasOne(d => d.PatientSurgery).WithMany(p => p.Surgeries)
                .HasForeignKey(d => d.PatientSurgeryId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_Surgery_PatientSurgery");

            entity.HasOne(d => d.SurgicalProcedure).WithMany(p => p.Surgeries)
                .HasForeignKey(d => d.SurgicalProcedureId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_Surgery_SurgicalProcedure");
        });

        modelBuilder.Entity<SurgeryAnesthesium>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Date).HasColumnType("date");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.PatientFileId).HasColumnName("PatientFileID");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.PatientSurgeryId).HasColumnName("PatientSurgeryID");

            entity.HasOne(d => d.PatientSurgery).WithMany(p => p.SurgeryAnesthesia)
                .HasForeignKey(d => d.PatientSurgeryId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_SurgeryAnesthesia_PatientSurgery");
        });

        modelBuilder.Entity<SurgicalProcedure>(entity =>
        {
            entity.ToTable("SurgicalProcedure");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
        });

        modelBuilder.Entity<Treatment>(entity =>
        {
            entity.ToTable("Treatment");

            entity.Property(e => e.Id).HasColumnName("ID");
            
            entity.Property(e => e.AdministrationMethod)
                .HasMaxLength(50)
                .HasComment("Defaul admin method (dosage, perfusion...) ");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.TreatmentCategoryId).HasColumnName("TreatmentCategoryID");
            entity.Property(e => e.ValueType).HasMaxLength(50);

            entity.HasOne(d => d.TreatmentCategory).WithMany(p => p.Treatments)
                .HasForeignKey(d => d.TreatmentCategoryId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_Treatment_TreatmentCategory");
        });

        modelBuilder.Entity<TreatmentCategory>(entity =>
        {
            entity.ToTable("TreatmentCategory");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID")
                .UseIdentityColumn(); 
            entity.Property(e => e.Name).HasMaxLength(150);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}