// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;

namespace StgMures.Server.Data
{
    public partial class StgMuresContext
    {
        private ISTGMuresContextProcedures _procedures;

        public virtual ISTGMuresContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new STGMuresContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ISTGMuresContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class STGMuresContextProcedures : ISTGMuresContextProcedures
    {
        private readonly StgMuresContext _context;

        public STGMuresContextProcedures(StgMuresContext context)
        {
            _context = context;
        }
    }
}
